### ISSUE TITLE
Privacy manifest file for iOS might be needed

### ISSUE THREAD

**Issue by oremlawi** [Flajt/flutter_donation_buttons#11]
Do you think that adding a privacy manifest to your library is needed? 

According to Apple's new policy, developers need to add `PrivacyInfo.xcprivacy` to their projects to declare some stuff related to user privacy.

For more information, please check [Apple's documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files).

**Comment by Flajt** [comment]
What I take from this documentation is no since it mentions: "... distributed as XCFrameworks, Swift packages, or Xcode projects...".

This package only provides some ui components and wraps url_launcher, so I don't have any native code in this lib. The package also doesn't collect any data, you can customize it to do so, but normaly it doesn't.

So my take would be no.
